### ISSUE TITLE
devise, omniauth and decl_auth

### ISSUE THREAD

**Issue by alec-c4** [stffn/declarative_authorization#104]
Hi,
I have strange app behavior built with devise, omniauth and decl_auth. App was developed with support for auth from twitter/facebook as described in 
http://asciicasts.com/episodes/235-omniauth-part-1
http://asciicasts.com/episodes/236-omniauth-part-2

and i have following auth config:
authorization do
  role :guest do
    description "Not logged in users and users not assigned to any group"
..............................
    ##### Comments
    has_permission_on :comments, :to => :read
    has_permission_on :comments, :to => [ :create, :flag, :destroy_comment, :update_comments_list ] if current_user
    has_permission_on :comments, :to => :manage do
      if_attribute :author => is { user }
    end
.................................
 end

Everything works fine for users registered by standard way, but not for users registered via twitter (only :read is available). Where should i see to find what causes this problem?

**Comment by stffn** [comment]
You are probably better off posting this problem to the mailing list since it is usage-related.  From a glance at your rules, I can say that the 'if current_user' is problematic as the rules are only read once in production mode.  Before you post to the mailing list, please check the debug output in the app log.
