### ISSUE TITLE
declarative_authorization's filter_resource_access method is not fully compatible with Rails namespaces

### ISSUE THREAD

**Issue by bluebird-communication** [stffn/declarative_authorization#164]
As declarative_authorization's **filter_resource_access** method does initialize singular instance variable, this lead to an issue when a model is namesapced. For example : generated with the help of **rails generate scaffold admin/movie title:string**

The model movie.rb is placed within an app/models/admin folder and it begins with a : 

```
  class Admin::Movie < ActiveRecord::Base
```

The controller singular instance variables in app/controllers/admin/movies_controller.rb should be initialized with : 

```
  @movie = Admin::Movie.find(params[:id])
```

Unfortunately, I guess it is initialised with : 

```
  @movie = Movie.find(params[:id])
```

Moreover, is there a way to use the find_by_id instead of the find method in declarative_authorization ?

**find** will always raise an error if the id can't be found. Which happen quite a lot if your users make use of the Restfull URL. Why otherwise would we bother to make Rails be **REST compliant ?**

Thanks for your answer on this

===== UPDATE =====

After some search in the code, I tried to setup a method load_movie, but this does'nt work.
If you look at line 521 to 530 in code of **filter_resource_access**, you'll notice that the **load_method** argument is not passed to the **filter_access_to** method :

```
    load_method = :"load_#{controller_name.singularize}"
    before_filter :only => members.keys do |controller|
      # load controller object
      if controller.respond_to?(load_method)
        controller.send(load_method)
      else
        controller.send(:load_controller_object, options[:context] || controller_name)
      end
    end
    filter_access_to :all, :attribute_check => true, :context => options[:context]
```

So even with a correct load_method defined in controller, it will fail.

**Comment by stffn** [comment]
You are correct, load method etc. are one way to manually overriding the loading of objects. It works, please check the tests and the documentation.  Thus, I'll close this issue.  If there are problems, please open a separate issue for this. If you need help on how to use a feature, please use the mailing list. This is for feature requests and bug reports only.

Regarding the original problem: you found the current way of handling namespaces.  I would like to have a better handling of namespaces as well, but cannot implement it due to time constraints. If a failing test case and a patch is provided, I will happily include that. We can track that problem in #120.
