### ISSUE TITLE
Using declarative_authorization with Rails 2

### ISSUE THREAD

**Issue by ltw** [stffn/declarative_authorization#70]
When using this gem with Rails 2, it tries to load Rails 3 dependencies due to the >= version specification in the config.

**Comment by stffn** [comment]
I haven't checked the behavior yet.  Still, do you have any proposal on how this should be fixed?

**Comment by radar** [comment]
Woah, this was quicker than I expected. Great work stffn!

I prompted ltw to file this issue and I've been writing a blog post this time in which I "formulated" that Bundler is the only One True Solution to fixing this problem. I can't think of anything else, unfortunately.

**Comment by ltw** [comment]
If you wanted to solve the Rails 2 issues (but prevent Rails 3 users), you could always use ~> 2.1 but obviously this isn't ideal.

**Comment by hellvinz** [comment]
a post about how to solve the problem
http://yehudakatz.com/2010/08/21/using-considered-harmful-or-whats-wrong-with/

**Comment by stffn** [comment]
decl_auth does support Rails 3, so ~> 2.1 does not help.  If you have both Rails 3 and Rails 2.x on your system, you might really need to use bundler.

**Comment by tricomsol** [comment]
yeah i am trying to deploy 2.3.9 version of my app on heroku and its loading rails 3 dependencies there and my application is crashing because of some gems which get loaded along with rails 3 like the rack gem and thin crashes there with already activated error. I think it should be removed from the dependencies for now until we find a better solution of handling this issue

**Comment by stffn** [comment]
At least until Heroku implements bundler support.  I just released 0.5.1 with that fix.

**Comment by radar** [comment]
Thank you, stffn.

**Comment by ltw** [comment]
Thanks for the fix, stffn. Much appreciated.
