### ISSUE TITLE
load_method called 2 times in version 0.5.1

### ISSUE THREAD

**Issue by jiongye** [stffn/declarative_authorization#72]
when I update the gem from 0.4.1 to 0.5.1, the option :load_method => method_name in the filter_access_to, called the method_name 2 times when the :attribute_check => true. everything works fine if I switch back to version 0.4.1.

**Comment by stffn** [comment]
I can reproduce this behavior.  The underlying reason is that in Rails 3 it is rather difficult to check whether a specific before_filter is already set.  So the rational was to rather set it twice than never.  What we need is a reliable way of checking whether there already was a filter_access_call in the current controller.  Unfortunately that is rather difficult as before_filters are removed differently from how e.g. class variables are handled.

Does your load method have side effects?  Or is this a performance issue for you?  The load method database request should be cached, right?

**Comment by jiongye** [comment]
No, my load method doesn't have side effect or there is a performance issue. I just wonder if this is a bug, so I reported it. Thanks.

**Comment by stffn** [comment]
Fixed in c1a2f93220714c396987dab4a594a9d8a8484dea
